complexity:
  LongParameterList:
    ignoreDefaultParameters: true
Compose:
  ComposableNaming:
    excludes: ['**/*Presenter.kt']
naming:
  InvalidPackageDeclaration:
    active: false
  FunctionNaming:
    excludes: ['**/*Test.kt']
    functionPattern: '[\w]+'
  MatchingDeclarationName:
    multiplatformTargets: ['android', 'jvm', 'wasmJs']
style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview', 'PreviewDayNight']
  UnusedPrivateProperty:
    excludes:
      - '**/*.gradle.kts'
