name: Setup Environment

inputs:
  workload_identity_provider:
    required: true

  service_account:
    required: true

  lfs:
    required: false
    default: false

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v6
      with:
        lfs: ${{ inputs.lfs }}

    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '21'

    - uses: gradle/actions/setup-gradle@v5

    - uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
