name: Publish Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'Publish Release')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - id: version
        run: |
          echo "name=$(./scripts/generate_version_name.sh "${{ github.run_number }}")" >> "$GITHUB_OUTPUT"
          echo "code=${{ github.run_number }}" >> "$GITHUB_OUTPUT"

    outputs:
      code: ${{ steps.version.outputs.code }}
      name: ${{ steps.version.outputs.name }}

  android:
    needs: [ version ]
    uses: ./.github/workflows/android-release.yml
    if: false
    with:
      version_code: ${{ needs.version.outputs.code }}
      version_name: ${{ needs.version.outputs.name }}
    secrets:
      ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
      BROWSER_API_KEY: ${{ secrets.BROWSER_API_KEY }}
      FASTLANE_SERVICE_ACCOUNT_KEY: ${{ secrets.FASTLANE_SERVICE_ACCOUNT_KEY }}
      FIREBASE_GOOGLE_SERVICES: ${{ secrets.FIREBASE_GOOGLE_SERVICES }}
      GOOGLE_SERVICE_ACCOUNT_ID: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
      KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

  github:
    needs: [ version, android ]
    runs-on: ubuntu-latest
    if: false

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          name: android-app-build-outputs
          path: android-app/build/outputs

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: |
          bundle exec fastlane android github \
            repository_name:"${{ github.repository }}" \
            api_bearer:"${{ secrets.GITHUB_TOKEN }}" \
            tag_name:"v${{ needs.version.outputs.name }}" \
            name:"Release v${{ needs.version.outputs.name }}" \
            commitish:"${{ github.sha }}"

  play:
    needs: [android]
    runs-on: ubuntu-latest
    if: false

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true

      - uses: actions/download-artifact@v8
        with:
          name: android-app-build-outputs
          path: android-app/build/outputs

      - run: echo ${{ secrets.FASTLANE_SERVICE_ACCOUNT_KEY }} | base64 --decode > android-app/src/main/play-store-key.json

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: |
          bundle exec fastlane android play

  web:
    needs: [version]
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v4

      - id: google-cloud-auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}

      - run: |
          npx firebase-tools deploy \
            --project ${{ steps.google-cloud-auth.outputs.project_id }} \
            --only hosting
