name: Renovate

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  renovate_main:
    name: Self-Hosted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}

      - uses: renovatebot/github-action@v46.2.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: renovate.json
