name: Terraform Plan

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Google Cloud
    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: 1password/install-cli-action@v2

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          token_format: access_token

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          app_id: ${{ secrets.GH_APP_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: v0.52.0

      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tflint --chdir=terraform --format=compact --minimum-failure-severity=warning

      - id: terraform
        env:
          TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
          TF_CLI_ARGS: -chdir=terraform -input=false
          TF_IN_AUTOMATION: true
        run: |
          terraform init
          terraform plan >/dev/null -lock-timeout=5m -out=.terraform/terraform.tfplan
          terraform show .terraform/terraform.tfplan -no-color

      - uses: thollander/actions-comment-pull-request@v3
        if: steps.terraform.outputs.stdout != ''
        with:
          message: "```${{ steps.terraform-plan.outputs.stdout }}```"
          comment-tag: terraform-plan
          mode: recreate
