name: Terraform Plan

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Google Cloud
    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: 1password/install-cli-action@v2

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}
          token_format: access_token

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          app_id: ${{ secrets.GH_APP_ID }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - env:
          TF_VAR_op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TF_VAR_gh_token: ${{ steps.token.outputs.token }}
          TF_CLI_ARGS: -chdir=terraform -input=false
          TF_IN_AUTOMATION: true
        run: |
          terraform init
          terraform providers
