name: Upgrade Yarn Lock

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upgradeYarnLock:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew kotlinWasmUpgradeYarnLock --console=plain

      - id: app-token
        uses: ./.github/actions/github-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - run: ./scripts/github_pull_request.sh
        env:
          COMMIT_MSG: "chore: upgrade yarn lock"
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
