name: Upgrade Yarn Lock

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upgradeYarnLock:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ID }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew kotlinWasmUpgradeYarnLock --console=plain

      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./scripts/github_pull_request.sh --add-all \
            --branch-name "${{ github.head_ref || github.ref_name }}" 
            --commit-msg "chore: upgrade yarn lock"
